### ISSUE TITLE
Units in Drude profile?

### ISSUE THREAD

**Issue by keflavich** [karllark/dust_extinction#188]
The modified Drude profile:
https://github.com/karllark/dust_extinction/blob/c5726582e126a1e7846226257d521a7ce17de9a6/dust_extinction/shapes.py#L165

matches the definition given in your 2021 paper:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/143715/209416587-90493624-0ce7-4225-8bc8-67ab97474bbe.png">

The argument of the exponential is `a (lambda-lambda0)`.  That has units left over if `a` is unitless, again following your paper:
<img width="515" alt="image" src="https://user-images.githubusercontent.com/143715/209416623-cd682da0-dedd-4309-ada2-3b962e218055.png">

Should `a` have units?  Or should `x-x0` be normalized to `(x-x0)/um`, say?  I haven't managed to track down the original definition.  I came to this error by trying to define my own Drude profile loosely approximating yours:
```python
def silicate_drude(lam, S1=1, a=-0.5, lambda0=9.7*u.um, gamma0=2*u.um):
    dlambda = (lam-lambda0).decompose()
    gamma = gamma0 / (1+np.exp(a*(lam-lambda0)
    dm = (gamma/lambda0)**2 / ((lam/lambda0 - lambda0/lam)**2 + (gamma/lam)**2)
    return dm * S1
```
and astropy rightly complained that you can't have units in the exponent.

**Comment by karllark** [comment]
You are quite correct.  the asymmetry parameter needs to have the inverse of the unis of lambda.  This was something I missed in my paper, but has been commented on since then.

You are the 2nd person to see this!   In work on the mid-ir spectral decomposition tool "PAHFIT", JD Smith also noted this.  There is some discussion on reformulating the equation for gamma in that repository (https://github.com/PAHFIT/pahfit/issues/205).  I do not think we have confirmed the proposed re-formulation has the same before yet.  So, for now I am keeping with the current formulation and will note the need for inverse wavelength units in my next paper that uses the modified Drude (to be submitted this week in fact).

**Comment by karllark** [comment]
In dust extinction, the input x values (in whatever units) are converted to inverse microns and then the units are stripped.   This is done to avoid such issues that also happen in the case of a polynomial model.  This is also done to avoid units issues with the fitting.  While units with fitting is possible, I have not been able to make this work with dust_extinction yet.  There is something I'm missing.

So, this means for dust_extinction, the asymmetry parameters should not have units and no change is needed.  

I agree that implementing this separately means you might wish to having units for a.
