### ISSUE TITLE
Question - Green et al Dust Maps

### ISSUE THREAD

**Issue by CarrieFilion** [karllark/dust_extinction#194]
Hello,
I'm working with spectra that have E(B-V) estimates from the Green et al 2019 dust maps and photometry that has been extinction-corrected using these E(B-V) values. I'd like to correct the spectra in a way that is consistent with how the photometry data were corrected. What are the best choices of input to the dust_extinction package to accomplish this?
Cheers,
Carrie

**Comment by krislars** [comment]
Hi Carrie,
It can be tricky to match spectroscopic extinction to photometric extinction.  Here is what I would do:  If you have photometry that was extinction corrected, then the person who did that correction had to convert from the one value output from the Green et al 2019 maps into other passbands, so I would start by asking that person how they did that conversion, specifically which law they used.  It is possible (likely?) that they used the reddening output from the Green maps code and multiplied by the [coefficients given in Table 1 of the Green et al 2019 paper](https://iopscience.iop.org/article/10.3847/1538-4357/ab5362#apjab5362t1).  Otherwise, and especially if your photometry is not Pan-STARRS or 2MASS, they certainly had to use some sort of law to convert.  That law might be a good choice for your spectra.  If they did use the Table 1 values, Green et al 2019 say that their law is similar to a recalibrated version of the RV = 3.3 reddening vector from Schlafly et al 2016.

I want to put a plug here that calculating your own reddening with synthetic photometry of spectra is not too hard.  [You can see an example I did here.](https://github.com/krislars/GaiaExtinctionTutorial/blob/main/GaiaExtinctionTutorial.ipynb)  One good check of whatever law you choose would be to calculate synthetic photometric reddening on your spectra and make sure it agrees with the photometry. 

Hope this helps!
Kristen

**Comment by schlafly** [comment]
Hi Carrie, Kristen,

If you're not aware of it, the discussion of the units in the Green+2019 maps here
http://argonaut.skymaps.info/usage#units
might be of value.  The normalizations become a mess because Green+19 targeted "SFD" normalization, and things like B & V and B-V aren't things that we measure with the photometry going into the Green or Schlafly papers.

If you want to use the same monochromatic extinction curve that Green+19 used, here's the approach.  Take the Schlafly+16 extinction curve
https://e.schlaf.ly/apored/extcurve.html
.  Then get the normalization right by computing E(g) (for example) from Green+19, and get the normalization of the Schlafly+16 extinction curve to match.  Specifically
```
ebv_g19 = 1
# table 1, http://argonaut.skymaps.info/usage#units
b19coeffs = np.array([3.518, 2.617, 1.971, 1.549, 1.263, 0.7927, 0.4690, 0.3026])
eg_g19 = ebv_g19 * b19coeffs[0]
ec = extcurve_s16.extcurve(0)  # normal R(V)
lam = extcurve_s16.lam0  
# grizyJHKW1W2 wavelengths in the context of the S16 analysis.
g_av1 = ec(lam[0])  # g extinction for A_5420 = 1
lamnew = 4000  # for example
e_lamnew = ec(lamnew) * eg_g19 / g_av1  # multiply by the A_g we want over the A_g at A(V) = 1.
# this is the extinction you want

# consistency check
expected_coeffs = ec(lam) * eg_g19 / g_av1
print(expected_coeffs[:-2] / b19coeffs)  # agrees to 4 significant figures
```
Sorry, that's a bit opaque, but hopefully it makes some sense.  More broadly, if you want to use some other extinction curve, you have to deal with the fact that Green+ modeled the broadband photometry with this extinction curve.  So there are choices to make between how to go from the Green+ mismodeling (since you think another extinction curve is more appropriate) and the right answer.  A simple prescription would be to do something like the above, but to instead use a color like g-K to do the transfer of the normalization.

**Comment by karllark** [comment]
Closing this issue as it looks to be answered.  Please reopen if this is not the case.
