### ISSUE TITLE
DOC: Extinction vs Attenuation

### ISSUE THREAD

**Issue by karllark** [karllark/dust_extinction#47]
This package provides extinction curves.  Extinction curves describe the effects of dust for the specific geometry of a single star behind a screen of dust.  Extinction is due to dust absorption and scattering *out* of the line-of-sight.

All other geometries require attenuation curves that include radiative transfer effects.  Radiative transfer effects include having significant dust scattered light in the measurement and mixing stars and dust together.  Examples are galaxies or regions of galaxies and circumstellar dust.

Formally:
All extinction curves are attenuation curves, but not all attenuation curves are extinction curves.

A separate package (dust_attenuation?) could/should be created to provide attenuation curves.  E.g., averages (e.g., Calzetti starburst law), results of dust radiative transfer models (e.g. DirtyGrid),  and various literature proposed shape models (e.g., Fall & Charlot).

**Comment by pllim** [comment]
Interesting. In terms of usage with `synphot`, which one is more appropriate?

**Comment by karllark** [comment]
It depends on the object being modeled.  If it is a star, then extinction.  If a galaxy, then attenuation.  While it is common for many to use these two interchangeably, it is still not correct.  :-)

**Comment by eteq** [comment]
I think it's definitely worth putting text like this in the docs, as prominently as possible.  As @karllark knows, I have have been tripped up by this, and I think a lot of dust non-experts (but who need to *use* dust experts' knowledge) would appreciate an explanation of this.

That said, I'm not sure I see the value of `dust_attenuation` as a *separate* package. It will likely lead to some amount of duplication of effort since a lot of the things you *do* with extinction/attenuation models are the same.  But there's a semantics problem now: is `dust_extinction.attenuation` or similar too much in violation of the "formally" wording @karllark has above?

**Comment by karllark** [comment]
I have a strong opinion that this should be a separate package.

The mechanics for supporting dust attenuation curves is significantly different if it is going to be done well.
I agree, that the mechanics for simple curves like the Calzetti Law are very similar/equivalent to what is done for dust extinction.  This is not the case for the more correct solutions that are based on dust radiative transfer calculations.  Those would require interpolating from tables based on radiative transfer calculations.  

The issue is that dust attenuation curves are fundamentally different than extinction curves in that their shape varies with the amount of dust.  The physics of radiative transfer clearly predicts this due to the mixing of stars embedded to different depths *and* the inclusion of dust scattered light in the observed beam.  This is true for any geometry other than that of an extinction curve with a star behind a screen of (distant) dust.  More details can be found in the literature from calculations with different radiative transfer codes.  One I like (for obvious reasons) is Witt & Gordon (2000, http://adsabs.harvard.edu/abs/2000ApJ...528..799W).

Treating attenuation curves like extinction curves (shape invariant with dust column) leads to *systematic* errors where (in general) lower dust columns are under corrected and higher dust columns are over corrected when unextinguishing (dereddening) data.

Having the two packages separate will make it easier to write, document, test, and maintain.
It will also emphasize the difference between extinction and attenuation.

In addition, having two packages would help in raising awareness of the differences between extinction and attenuation.

**Comment by pllim** [comment]
@karllark , if you separate into two packages, is it a common use case that most users would only need **one or the other**? If users end up using both packages in their research anyway, it might as well just be a single package.

**Comment by karllark** [comment]
@pllim , Yes.  In general, most use cases are separate.  

If you are working on stars (in our or another galaxy), you only use extinction curves (I have not heard of anyone using attenuation curves for stars).  People working on stars that have circumsteller dust (e.g., Young Stellar Objects) generally use radiative transfer models to handle the dust getting the correct attenuation behavior.

If you are work on galaxies, you should only use attenuation curves.  Lots of people working on galaxies also use extinction curves even through this leads to systematic biases.  I do believe that this community is slowly becoming aware that extinction curves are not appropriate.  This is partially due to having broader wavelength coverage of galaxy SEDs where the systematic biases are easier to diagnose.  The lack of a good package providing attenuation curves based on radiative transfer models is one of the barriers to more people using attenuation curves.  At least that is my reading talking to a number of those working in this area.

**Comment by pllim** [comment]
Thanks for the explanation!

**Comment by eteq** [comment]
@karllark - I see all your points here.  As we discussed out-of-band, there's also an argument that extinction might move into the core at some point, while attention probably would not.

All that said, my one concern is about maintainability: in my experience having more packages often means more work and less user attention because there's "two" places to look/import/install etc.  I think your argument is that in this case it's a *good* thing, because these are different enough that users should *know* that.  If you're happy dealing with the added maintenance burden and think it's not a big worry that about the "marketing" aspect, then I'm all for that.  Just wanted to bring up the fact that there's a potential user-base tradeoff here.

**Comment by karllark** [comment]
@eteq - given all this, two packages is the plan.  In fact, I've gone ahead and setup the bones of the dust_attenuation package.  I'll work on adding basic issues, docs, etc. over the next few days.  And try and get in the Calzetti starburst attenuation model to provide a starting point.

**Comment by karllark** [comment]
Still need good documentation here and in the dust_attenuation package about the differences.  And pointing between the packages.

**Comment by eteq** [comment]
@karllark - Another thing to consider to help them them be more discoverable: write an Astropy tutorial that demonstrates the use of *both* (perhaps, depending on progress in the various areas, also using `specutils`).  One of the things that the tutorials are aimed at is workflows that span multiple packages, so that seems right up this alley.

**Comment by karllark** [comment]
The dust_extinction and dust_attenuation packages now mention each other.  But the detailed discussion on the differences between extinction/attenuation is still needed.  

Another reference to include is Krugel 2009.  https://ui.adsabs.harvard.edu//#abs/2009A&A...493..385K/abstract
But need to emphasize that for extinction curves a local background is subtracted, so scattering into the line of sight is minimized.  Not sure if such background subtraction was included in the Krugel 2009 analysis (more careful reading needed).

**Comment by karllark** [comment]
The two pull requests related to this issue are ready for review.  @eteq and @pllim do you have the time for such a review?  Even a quick check would be appreciated.  This is completely a documentation update and there are plots.  Not sure how to provide the rendered docs in a way that is easy to review.  Suggestions welcome.

The two pull requests are (to be explicit):
https://github.com/karllark/dust_extinction/pull/79
https://github.com/karllark/dust_attenuation/pull/39

**Comment by karllark** [comment]
Closing this issue as the basic documentation has been merged.  Better docs always possible.  A new issue is always welcome on this topic.
