### ISSUE TITLE
Problem with M14 model

### ISSUE THREAD

**Issue by karllark** [karllark/dust_extinction#76]
@krislars : In looking over the newly build documentation, I noticed that there is a *2nd* bump in the UV for the M14 model for the Rv=5.5 plot.  Have a look in the model_flavors documentation (URL below) and tell me what you think.  I'm pretty sure this is not right, but you are the expert on M14.

https://dust-extinction.readthedocs.io/en/latest/dust_extinction/model_flavors.html

**Comment by krislars** [comment]
Oh!  That doesn't look right.  Working on it now.

**Comment by krislars** [comment]
Or maybe it is right.  

Their paper says: "UV extinction is a different and difficult issue that is not measured in this paper even though a functional form is provided. More specifically, the routine [that I converted into Python here] may work for low values of R5495 (as CCM does) but is guaranteed to fail for high values of R5495. The reason is that the jump seen for R5495 = 5.0 and 7.0 around x = 3.9μm<sup>-1</sup> is not physical but a product of tying up the results of this paper in the optical with those of CCM in the UV."

Let me look into it more.  It's not pretty, that's for sure.

**Comment by krislars** [comment]
The bump is in their figures, too: 

https://www.aanda.org/articles/aa/full_html/2014/04/aa23439-14/F11.html

**Comment by krislars** [comment]
Yes, warnings all the places!

I dived into the 30-ish papers that reference M14, and none of them use the UV curve.  All the investigations (eg [Schlafly et al 2016](http://iopscience.iop.org/article/10.3847/0004-637X/821/2/78/meta) and my own personal interest) are in the optical and NIR.  Even M's own follow-on work ([Maiz Apellaniz & Barba 2018](http://adsabs.harvard.edu/abs/2018A%26A...613A...9M)) which states unequivocally that M14 is better than CCM or F99, only uses the curve through Johnson U.

Perhaps it would be a good idea to truncate the allowable wavelengths.  Question is, where?

**Comment by karllark** [comment]
This might be the best solution.  If one was to need UV, then I would assume it would be better to use a different model.  Truncation should be easy, just change the allowed x_range at the top of the file with the model (e.g., x_range_M14).  That should do the trick.

**Comment by krislars** [comment]
I will do that.  I'll also need to change the tests, and I'll add a line in the documentation.

**Comment by krislars** [comment]
Ready to close this?

**Comment by karllark** [comment]
Yep.
